language: r

cache: packages

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE


bioc_packages: limma sva impute

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'