language: r

cache: packages

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

bioc_packages: limma
bioc_packages: sva
bioc_packages: impute

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'