language: r

cache: packages

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

before_install:
  - Rscript -e "source('https://bioconductor.org/biocLite.R'); biocLite(c('limma', 'sva', 'impute'))"
  - Rscript -e "install.packages("Rmosek", type="source", repos="http://download.mosek.com/R/7")"

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'