language: r

r: 
  - 3.1

cache: packages

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - Rscript -e "source('http://bioconductor.org/biocLite.R'); biocLite(c('limma', 'sva', 'impute'))"

