language: r

cache: packages

env:
  - _R_CHECK_FORCE_SUGGESTS_=false

before_install:
  - Rscript -e "source('https://bioconductor.org/biocLite.R'); biocLite(c('limma', 'sva', 'impute'))"

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'